name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            cmake -S . -B build -DBUILD_TESTING=ON
          else
            cmake -S . -B build -DBUILD_TESTING=ON -DENABLE_SANITIZERS=ON
          fi

      - name: Build
        shell: bash
        run: cmake --build build -j

      - name: Test
        shell: bash
        run: ctest --test-dir build -j2 --output-on-failure

